# group:
  netdata_server:
    name: Server Netdata
    entities:
      - sensor.server_cpu_usage
      - sensor.server_ram_used
      - sensor.server_load_1min
      - sensor.server_disk_used
      - sensor.server_disk_available

  netdata_router:
    name: Router Netdata
    entities:
      - sensor.router_cpu_usage
      - sensor.router_ram_used
      - sensor.router_load_1min
      - sensor.router_uptime

  netdata_router_fping:
    name: Router FPing
    entities:
      - sensor.router_ping_google_avg
      - sensor.router_ping_google_max
      - sensor.router_ping_google_quality
      - sensor.router_ping_cloudflare_avg
      - sensor.router_ping_cloudflare_quality

  netdata_router_wan:
    name: Router WAN Traffic
    entities:
      - sensor.router_wan_received
      - sensor.router_wan_sent

  netdata_router_wifi:
    name: Router WiFi Traffic
    entities:
      - sensor.router_wifi_5ghz_received
      - sensor.router_wifi_5ghz_sent
      - sensor.router_wifi_2_4ghz_received
      - sensor.router_wifi_2_4ghz_sent
