# automation:

# - Cuando, tanto el termometro de fuera como el de dentro empiecen a subir seguramente 
#     la temperatura esté subiendo así que a cerrar ventanas. Comprobar con la tendencia de AEMET.
# - Cuando, la tendencia del termometro de fuera sea a la baja y cruce la del termometro de dentro
#     es el momento de abrir las ventanas.

  - alias: AUT-Mark windows preferred status as close
    mode: queued
    triggers:
      - platform: template
        value_template: "{{ states('binary_sensor.environment_001_temperature_rising') and states('binary_sensor.dyson_01_temperature_rising') }}"
        # for: "00:10:00"
        for: "01:30:00"
    actions:
      - service: input_select.select_option
        data:
          entity_id: input_select.windows_preferred_status
          option: Close

  - alias: AUT-Mark windows preferred status as open
    mode: queued
    triggers:
      - platform: template
        value_template: "{{ states('binary_sensor.environment_001_temperature_falling') and (states('sensor.ble_environment_001_temperature') < states('sensor.dyson_01_temperature')) }}"
        for: "00:10:00"
    # conditions:
    #   - platform: template
    #     value_template: "{{ states('binary_sensor.environment_001_temperature_falling') }}"
    #     # for: "00:10:00"
    #     for: "01:00:00"
    actions:
      - service: input_select.select_option
        data:
          entity_id: input_select.windows_preferred_status
          option: Open
