# homeassistant:
#   customize:
    sensor.ble_conductivity_flora_001: &customization-flora-001
      friendly_name: flora-001

    sensor.ble_illuminance_flora_001: *customization-flora-001
    sensor.ble_moisture_flora_001: *customization-flora-001
    sensor.ble_temperature_flora_001: *customization-flora-001
    sensor.ble_battery_flora_001: *customization-flora-001
