# group:
  flora_001:
      entities:
        - sensor.ble_conductivity_flora_001
        - sensor.ble_illuminance_flora_001
        - sensor.ble_moisture_flora_001
        - sensor.ble_temperature_flora_001
        - sensor.ble_battery_flora_001
