# plant:
  flora-001:
    sensors:
      battery: sensor.mi_batt_c47c8d6b1a91
      moisture: sensor.mi_m_c47c8d6b1a91
      temerature: sensor.mi_t_c47c8d6b1a91
      conductivity: sensor.mi_c_c47c8d6b1a91
      brightness: sensor.mi_l_c47c8d6b1a91
    # min_battery: 20
    # min_moisture:
    # max_moisture:
    # min_temperature:
    # max_temperature:
    # min_brightness:
    # max_brightness:
