# plant:
  flora_001:
    sensors:
      battery: sensor.ble_battery_flora_001
      moisture: sensor.ble_moisture_flora_001
      temperature: sensor.ble_temperature_flora_001
      conductivity: sensor.ble_conductivity_flora_001
      brightness: sensor.ble_illuminance_flora_001
    # min_battery: 20
    # min_moisture:
    # max_moisture:
    # min_temperature:
    # max_temperature:
    # min_brightness:
    # max_brightness:
