# automation:

  # When low power is detected, probably we would like to turn off the power plug.
  - alias: AUT-Turn off man-003
    trigger:
      - platform: numeric_state
        entity_id: sensor.man_003_energy_current
        below: 0.05
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        entity_id:
          - switch.man_003_left
          - switch.man_003_right
      - service: homeassistant.turn_on
        entity_id: script.notify_in_home_or_all
        data:
          variables:
            title: 'Kitchen power plug turned off'
            message: 'Ey, I (`AUT-Turn off man-003`) detected low power consumption in the kitchen power plug so I turned off *both*'
            keyboard:
              - 'Turn on *Left*:/turn_on switch.man_003_left, Turn on *Right*:/turn_on switch.man_003_right'
