# automation:

  # When low power is detected, probably we would like to turn off the power plug.
  - alias: AUT-Turn off man-003
    triggers:
      - platform: numeric_state
        entity_id: sensor.man_003_energy_current
        below: 0.3
        for:
          minutes: 10
    conditions:
      - condition: state
        entity_id: input_boolean.man_003_auto_poweroff
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: switch.man_003_left
            state: 'on'
          - condition: state
            entity_id: switch.man_003_right
            state: 'on'
    actions:
      - service: switch.turn_off
        entity_id:
          - switch.man_003_left
          - switch.man_003_right
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.man_003_auto_poweroff
      - service: script.notify_in_home_or_all
        data:
          title: 'Kitchen power plug turned off'
          message: |
            Ey, I (`AUT-Turn off man-003`) detected low power consumption in the kitchen power plug so I turned off *both*.\n
            Additionally, I disabled auto turn off kitchen power plug
          data:
            inline_keyboard:
              - 'Turn on Left:/turn_on switch.man_003_left, Turn on Right:/turn_on switch.man_003_right'
