# google_assistant:
  # entity_config:
    switch.man_003_left:
      room: Kitchen
      expose: True
      aliases:
        - Enchufe izquierdo
        - Enchufe cocina izquierdo

    switch.man_003_right:
      room: Kitchen
      expose: True
      aliases:
        - Enchufe derecho
        - Enchufe cocina derecho
