homeassistant:
  # Name of the location where Home Assistant is running
  name: MomaHome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret momahome_latitude
  longitude: !secret momahome_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret momahome_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  ## URL
  external_url: !secret momahome_url
  internal_url: !secret momahome_url
  # Customization file
  customize: !include_dir_merge_named __auto_generated-config/customize/
  auth_mfa_modules:
    - type: totp
      name: Authenticator app
    - type: notify
      message: 'Hey, that is your access code: `{}`'
  # packages: !include_dir_named packages
# https://www.home-assistant.io/integrations/aemet/
logger:
  default: info
  logs:
    homeassistant.components.nmap_tracker.device_tracker: warn
    homeassistant.components.ddwrt.device_tracker: warn
    homeassistant.components.discovery: warn
    homeassistant.components.upnp: warn

lovelace:
  mode: yaml
  # Add more dashboards
  ### Default continue in ui-lovelace.yaml
  dashboards:
    # lovelace-overview: # Needs to contain a hyphen (-)
    #   mode: yaml
    #   filename: ui-lovelace.yaml
    #   title: Overview
    #   icon: mdi:tools
    #   show_in_sidebar: true
    #   require_admin: true
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: All entities (autogenerated)
      icon: mdi:arrow-all
      show_in_sidebar: true
      require_admin: true
  resources:
    - type: module
      url: /local/external-cards/xiaomi-vacuum-map-card.js
    - type: module
      url: /local/external-cards/uptime-card.js
    - type: module
      url: /local/external-cards/mini-graph-card-bundle.js
    - type: module
      url: /local/external-cards/tv-card.js
    - type: module
      url: /local/external-cards/googletimers-card.js

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
  # include:
  exclude:
    # domains:
    #   - automation
    #   - updater
    entities:
      - sun.sun # Don't record sun data
      # - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      # - sensor.date

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Info about updates
updater:
  include_used_components: true

http:
  server_port: 8123
  ## Configuration to use behind a proxy
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8
  ## Auto ban IPs based in failed logins attemps
  ip_ban_enabled: true
  login_attempts_threshold: 10

# Discover some devices automatically
discovery:

mqtt:
  broker: 192.168.200.7
  port: 1883
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password

# Server
# pi_hole: !include_dir_merge_named __auto_generated-config/pi_hole/
duckdns: !include_dir_merge_named __auto_generated-config/duckdns/
speedtestdotnet: !include_dir_merge_named __auto_generated-config/speedtestdotnet/
apcupsd: !include_dir_merge_named __auto_generated-config/apcupsd/
binary_sensor: !include_dir_merge_list __auto_generated-config/binary_sensor/

google_assistant: !include_dir_merge_named __auto_generated-config/google_assistant/

device_tracker: !include_dir_merge_list __auto_generated-config/device_tracker/

input_select: !include_dir_merge_named __auto_generated-config/input_select/

input_number: !include_dir_merge_named __auto_generated-config/input_number/

input_boolean: !include_dir_merge_named __auto_generated-config/input_boolean/

ble_monitor:
  # https://github.com/custom-components/ble_monitor
  ## Hey ! If a error occur don't worry, HA needs disable that component and restart
  discovery: False
  restore_state: True
  active_scan: False
  devices: !include_dir_merge_list __auto_generated-config/ble_monitor_device/

browser_mod:
  # https://github.com/thomasloven/hass-browser_mod

delete:
  # https://github.com/chomupashchuk/delete-file-home-assistant

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

telegram_bot: !include_dir_merge_list __auto_generated-config/telegram_bot/

timer: !include_dir_merge_named __auto_generated-config/timer/


input_datetime: !include_dir_merge_named __auto_generated-config/input_datetime/

# vacuum: !include_dir_merge_list __auto_generated-config/vacuum/

camera: !include_dir_merge_list __auto_generated-config/camera/

switch: !include_dir_merge_list __auto_generated-config/switch/

light: !include_dir_merge_list __auto_generated-config/light/

plant: !include_dir_merge_named __auto_generated-config/plant/

# Now forced to be managed from UI. Release 2021.6
# tuya: !include_dir_merge_named __auto_generated-config/tuya/

# dyson: !include_dir_merge_named __auto_generated-config/dyson/

# shell_command:
#   # https://philhawthorne.com/automating-your-shopping-list-with-home-assistant-and-grocy/
#   grocy_consume_item: "curl -X POST https://{{server_ip}}/api/stock/products/{{product_id}}/consume -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'GROCY-API-KEY: {{grocy_key}}' -H 'cache-control: no-cache' -d '{ \"amount\": {{amount}},  \"transaction_type\": \"consume\",  \"spoiled\": false }'"


notify: !include_dir_merge_list __auto_generated-config/notify/

person: !include_dir_merge_list __auto_generated-config/person/

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret momahome_latitude
    longitude: !secret momahome_longitude
    radius: 50
    icon: mdi:home-variant
  - name: Man-Work
    latitude: !secret manolo_work_latitude
    longitude: !secret manolo_work_longitude
    radius: 120
    icon: mdi:map-search


sensor: !include_dir_merge_list __auto_generated-config/sensor/
group: !include_dir_merge_named __auto_generated-config/group/
automation: !include_dir_merge_list __auto_generated-config/automation/
script: !include_dir_merge_named __auto_generated-config/script/
scene: !include_dir_merge_list __auto_generated-config/scene/
