
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/

recorder_db_url: postgresql://<user>:<password>@<uri>:<port>/<db>

telegram_api_key: <secret_api_key>

tuya_username: <tuya_email>
tuya_password: <tuya_password>

tile_username: <tile_email>
tile_password: <tile_passwd>

mqtt_username: <mqtt_email>
mqtt_password: <mqtt_passwd>

tile_device_manolo_keys: device_tracker.tile_manolo
# tile_device_monica_keys:

DDWRT_USERNAME: <ddwrt_user>
DDWRT_PASSWORD: <ddwrt_pass>
DDWRT_SNMP_RO: <ddwrt_snmp>

xiaomi_vacuum_token_0: <xiaomi_vacuum_token_0_________>

duckdns_token: <duckdns_token>

momahome_latitude: 0.0000
momahome_longitude: 0.0000
momahome_elevation: 0

manolo_work_latitude: 0.0000
manolo_work_longitude: 0.0000

duckdns_domains: <duckdns_domain>

sensor_miflora_mac: <sensor_miflora_mac>
## This is really hard to obtain but... https://github.com/custom-components/sensor.mitemp_bt/issues/7#issuecomment-595874419
sensor_environment-001_bindkey: <sensor_environment-001_bind_key>

telegram_userid_manolo: 012345678
telegram_userid_monica: 012345678

switch_ir_living_room_mac: 00:00:00:00:00:00

person_user_id_manolo: <person_user_id_manolo>
person_user_id_monica: <person_user_id_monica>
