# google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include ../../google_assistant_service_account.json
  report_state: true
  # expose_by_default: true
  exposed_domains:
    - switch
    - light
    - sensor
    - vacuum
    # - scene
  entity_config: !include_dir_merge_named ../../__auto_generated-config/google_assistant_entities/
