# automation:
  - alias: AUT-LightForReadOnBed
    initial_state: 'on'
    trace:
      stored_traces: 5
    mode: 'queued'
    trigger:
      - platform: device
        domain: zha
        device_id: fc590f181eaddcfcfc6d6984c7ec76c5
        type: remote_button_double_press
        subtype: turn_on
    action:
      - service: scene.turn_on
        entity_id: scene.ReadOnBedroom
        # data:
        #   # If enabled, brightness didn't change
        #   transition: 2.5
  - alias: AUT-LightForSleep
    initial_state: 'on'
    trace:
      stored_traces: 5
    mode: 'queued'
    trigger:
      - platform: device
        domain: zha
        device_id: fc590f181eaddcfcfc6d6984c7ec76c5
        type: remote_button_short_press
        subtype: turn_on
    action:
      - service: scene.turn_on
        entity_id: scene.BeforeSleepOnBedroom
        # data:
        #   # If enabled, brightness didn't change
        #   transition: 2.5
  - alias: AUT-MaxLightOnBedroom
    initial_state: 'on'
    trace:
      stored_traces: 5
    mode: 'queued'
    trigger:
      - platform: device
        domain: zha
        device_id: fc590f181eaddcfcfc6d6984c7ec76c5
        type: remote_button_long_press
        subtype: dim_up
    action:
      - service: scene.turn_on
        entity_id: scene.MaxIlluminationOnBedroom
        # data:
        #   # If enabled, brightness didn't change
        #   transition: 2.5
