# automation:
  - alias: AUT-Test_Ikea_button
    initial_state: 'on'
    trace:
      stored_traces: 5
    mode: 'queued'
    trigger:
      - platform: device
        domain: zha
        device_id: d738497a8cef8b04d4c8f51710a9074d
        type: remote_button_short_press
        subtype: turn_on
    action:
      - service: scene.turn_on
        entity_id: scene.night
      - service: notify.manolo
        data:
          title: "*Example*"
          message: "We properly detect the button!"

