# sensor:
  - platform: mitemp_bt
    ## Hey ! If a error occur don't worry, HA needs disable that component and restart
    batt_entities: True
    encryptors:
      'A4:C1:38:5C:C1:2A': !secret sensor_environment-001_bindkey
    whitelist:
      - !secret sensor_miflora_mac
