# person:
  - name: Manolo
    id: person_manolo
    user_id: !secret person_user_id_manolo
    device_trackers:
      - device_tracker.manolo_movil
      - device_tracker.manolo_pc7
      - binary_sensor.man_005_tile_llaves_manolo
      - !secret tile_device_manolo_keys

  - name: Monica
    id: person_monica
    user_id: !secret person_user_id_monica
    device_trackers:
      - device_tracker.moni_movil
      - device_tracker.iphone_2
      - binary_sensor.man_005_tile_llaves_monica
