# automation:
  - alias: AUT-ManoloWorkMode
    initial_state: 'on'
    trace:
      stored_traces: 5
    mode: 'queued'
    trigger:
      - platform: device
        domain: zha
        device_id: d207bfdca66e300274e57e4d3ff883f6
        type: remote_button_short_press
        subtype: button_1
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.man_001
  - alias: AUT-ManoloNotWorkingMode
    initial_state: 'on'
    trace:
      stored_traces: 5
    mode: 'queued'
    trigger:
      - platform: device
        domain: zha
        device_id: d207bfdca66e300274e57e4d3ff883f6
        type: remote_button_double_press
        subtype: button_1
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.man_001

