# automation:
  - alias: AUT-New device found
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.manolo
        data_template:
          title: "*ALERT: New device found !*"
          message: 'New device called `{{ trigger.event.data.host_name }}` with MAC `{{ trigger.event.data.mac }}` found'

  - alias: AUT-New Release
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.manolo
      data_template:
        title: "*New Home Assistant Release*"
        message: "Home Assistant  {{ states('updater.updater') }}  is now available"

  - alias: AUT-Notify failed login attempt
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: persistent_notification.http_login
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      service: notify.manolo
      data_template:
        title: "*{{ state_attr('persistent_notification.http_login', 'title') }} !*"
        message: "{{ state_attr('persistent_notification.http_login', 'message') }}"