
vacuum_zone:
  alias: "Vacuum a zone with coordinates"
  fields:
    zone_to_clean:
    n_repeats:
    approach_steps:
  sequence:
    - service: system_log.write
      data:
        logger: mlr.script.tests
        message: >
          Ey, this is the value in 1:
          {{ zone_to_clean | default('the string was empty') }}
          ,
          {{ n_repeats | default('the string was empty') }}
          ,
          {{ approach_steps | default('the string was empty') }}
    # # Loop over approach_steps
    # - while: >
    #     {{ (approach_steps is defined) and (repeat.index <= approach_steps|length) }}
    #   sequence:
    #     - service: xiaomi_miio.vacuum_goto
    #       data:
    #         entity_id: vacuum.xiaomi_vacuum
    #         x_coord: >
    #           {{ approach_steps[repeat.index - 1][0] }}
    #         y_coord: >
    #           {{ approach_steps[repeat.index - 1][1] }}
    #     ## Probably we need to wait until goto finish

    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum
        repeats: "{{ n_repeats }}"
        zone: "{{ zone_to_clean }}"

vacuum_room:
    alias: "Start cleaning"
    variables:
      defined_zones:
        corridor:
          approach_steps: []
          coordinates: [[26876,24122,29376,25122]]
        eat_area:
          approach_steps: []
          coordinates: [[25286,25553,27386,27553]]
        study_room:
          approach_steps: []
          coordinates: [[29477,21816,31677,25216]]
        bathroom:
          approach_steps: []
          coordinates: [[26861,21740,28961,24190]]
        bedroom:
          approach_steps: []
          coordinates: [[23302,21376,26952,25076]]
        hall:
          approach_steps: []
          coordinates: [[29854,28330,31404,30980]]
        kitchen:
          approach_steps: []
          coordinates: [[31439,27363,33939,30413]]
        living_room:
          approach_steps: []
          coordinates: [[24507,25175,31207,28525]]
    sequence:
      - service: vacuum.set_fan_speed
        entity_id: vacuum.xiaomi_vacuum
        data:
          entity_id: vacuum.xiaomi_vacuum
          fan_speed: >
            {{states('input_select.vacuum_zone_fan_speed')}}
      - variables:
          selected_zone: >
            {% set selected_zone_name = (states("input_select.vacuum_zone_room_selected")|regex_replace(find=' ', replace='_', ignorecase=False)) %}
            {{ defined_zones[selected_zone_name] }}
      - service: system_log.write
        data:
          logger: mlr.script.tests
          message: >
            Ey, this is the value in 0:
            {{ selected_zone | default('the string was empty') }}
            but seletected_zone_name must be:
            {{ (states("input_select.vacuum_zone_room_selected")|regex_replace(find=' ', replace='_', ignorecase=False)) }}
      - service: script.turn_on
        data:
          entity_id: script.vacuum_zone
          variables:
            zone_to_clean: >
              {{ selected_zone.coordinates }}
            n_repeats: >
              {{(states('input_number.vacuum_zone_repeats')|int)}}
            approch_steps: >
              {{ selected_zone.approach_steps }}
