
vacuum_room:
  alias: "Vacuum start cleaning a zone"
  variables:
    defined_zones:
      # That values must be the same than 'input_select.vacuum_zone_room_selected' but changing " " with "_"
      corridor:
        coordinates: [[26876,24122,29376,25122]]
        # approach_steps: []
      eat_area:
        coordinates: [[25286,25553,27386,27553]]
      study_room:
        coordinates: [[29477,21816,31677,25216]]
      bathroom:
        coordinates: [[26861,21740,28961,24190]]
      bedroom:
        coordinates: [[23302,21376,26952,25076]]
      hall:
        coordinates: [[29854,28330,31404,30980]]
      kitchen:
        coordinates: [[31439,27363,33939,30413]]
      living_room:
        coordinates: [[24507,25175,31207,28525]]
  sequence:
    - variables:
        selected_zone: >
          {% set selected_zone_name = (states("input_select.vacuum_zone_room_selected")|regex_replace(find=' ', replace='_', ignorecase=False)) %}
          {{ defined_zones[selected_zone_name] }}

    - variables:
        zone_to_clean: >
          {{ selected_zone.coordinates }}
        n_repeats: >
          {{(states('input_number.vacuum_zone_repeats')|int)}}
        # approch_steps: >
        #   {{ selected_zone.approach_steps }}
    - service: vacuum.set_fan_speed
      entity_id: vacuum.xiaomi_vacuum
      data:
        entity_id: vacuum.xiaomi_vacuum
        fan_speed: >
          {{states('input_select.vacuum_zone_fan_speed')}}
    - service: script.vacuum_zone
      data:
        zone_to_clean: >
          {{ selected_zone.coordinates }}
        n_repeats: >
          {{(states('input_number.vacuum_zone_repeats')|int)}}
        approch_steps: >
          {{ selected_zone.approach_steps }}
    # - service: system_log.write
    #   data:
    #     logger: mlr.script.tests
    #     message: >
    #       Ey, this is the value in 1:
    #       {{ selected_zone | default('the string was empty') }}
    #       ,
    #       {{ (states("input_select.vacuum_zone_room_selected")|regex_replace(find=' ', replace='_', ignorecase=False)) }}
    #       ,
    #       {{ zone_to_clean | default('the string was empty') }}
    #       ,
    #       {{ n_repeats | default('the string was empty') }}
    #       ,
    #       {{ approach_steps | default('the string was empty') }}
    # # Loop over approach_steps
    # - while: >
    #     {{ (approach_steps is defined) and (repeat.index <= approach_steps|length) }}
    #   sequence:
    #     - service: xiaomi_miio.vacuum_goto
    #       data:
    #         entity_id: vacuum.xiaomi_vacuum
    #         x_coord: >
    #           {{ approach_steps[repeat.index - 1][0] }}
    #         y_coord: >
    #           {{ approach_steps[repeat.index - 1][1] }}
    #     ## Probably we need to wait until goto finish and also add manual steps to enter in the unknown zone

    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum
        repeats: "{{ n_repeats }}"
        zone: "{{ zone_to_clean }}"
