title: MomaHome
views:
    # View tab title.
  - title: Home
    cards:
      - type: markdown
        title: Lovelace
        content: >
          Welcome to my **MomaHome** ! !
      - title: Cosas encendidas
        type: entity-filter
        show_header_toggle: true
        entities:
          - entity: switch.85304541b4e62d735f80_1
            name: Enchufe cocina doble izq.
          - entity: switch.85304541b4e62d735f80_2
            name: Enchufe cocina doble der.
          - entity: switch.man_001
            name: Enchufe luz salón
          # - entity: switch.02007254dc4f22ff4f45
          #   s/n: xxxx...xx 3401
          #   name: Luz salón
          - device_tracker.print_canon_mx920
        state_filter:
          - "on"
          - "home"
      - type: entities
        # title: People status
        show_header_toggle: false
        entities:
          - entity: sensor.manolo_status
            secondary_info: last-changed
          - entity: sensor.monica_status
            secondary_info: last-changed
      - title: House
        type: picture-elements
        image: /local/my_config/home_map.jpg
        # image: /local/floorplan.png
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.living_room_light
            style:
              top: 54%
              left: 57%
              "--paper-item-icon-color": black
          - type: state-icon
            tap_action:
              action: more-info
            entity: group.power_socket_double_001
            # entity: group.vacuum_room
            style:
              top: 15%
              left: 94%
              "--paper-item-icon-color": black
          - type: state-icon
            tap_action:
              action: toggle
            entity: switch.tv_samsung_on
            icon: mdi:television-classic
            state_filter:
              "off": --paper-item-icon-color=pink
            style:
              top: 54%
              left: 27%
              "--paper-item-icon-color": black
          - type: state-icon
            tap_action:
              action: more-info
            entity: vacuum.xiaomi_vacuum
            style:
              top: 57%
              left: 23%
              "--paper-item-icon-color": black
          - type: conditional
            tap_action:
              action: none
            conditions:
              - entity: device_tracker.print_canon_mx920
                state: home
            elements:
              - type: state-icon
                tap_action:
                  action: more-info
                entity: device_tracker.print_canon_mx920
                style:
                  top: 80%
                  left: 80%
                  "--paper-item-icon-color": yellow
          - type: state-label
            entity: sensor.outside_temperature
            style:
              top: 45%
              left: 88%
          # - type: service-button
          #   title: Turn lights off
          #   style:
          #     top: 95%
          #     left: 60%
          #   service: homeassistant.turn_off
          #   service_data:
          # Didn't work from 0.104: https://www.home-assistant.io/blog/2020/01/15/release-104/
          #     entity_id: group.all_lights
          - type: icon
            icon: mdi:home
            tap_action:
              action: navigate
              navigation_path: /lovelace/0
            style:
              top: 10%
              left: 10%
      # - title: Luces
      #   type: entities
      #   entities:
        # Didn't work from 0.104: https://www.home-assistant.io/blog/2020/01/15/release-104/
      #     - group.all_lights

  - title: Net
    cards:
      - type: history-graph
        title: 'Net Speed'
        hours_to_show: 48
        entities:
          # - group.home_speed
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload
      # - type: vertical-stack
      #   cards:
      #     - type: picture-entity
      #       entity: camera.demo_camera
      #       show_info: false
      #     - type: entities
      #       entities:
      #         - binary_sensor.movement_backyard
      - type: history-graph
        title: 'Router'
        hours_to_show: 5
        entities:
          # - group.net_router_statistics
          # - sensor.wireless_broadband_router_packets_received
          # - sensor.wireless_broadband_router_kbyte_sec_sent
          # - sensor.wireless_broadband_router_kbyte_sec_received
          # - sensor.wireless_broadband_router_bytes_sent
          # - sensor.wireless_broadband_router_packets_sec_received
          # - sensor.wireless_broadband_router_packets_sent
          # - sensor.wireless_broadband_router_bytes_received
          # - sensor.wireless_broadband_router_packets_sec_sent
          - sensor.router_cpu_load
          - sensor.router_ram_free
      - type: history-graph
        title: 'PiHole'
        hours_to_show: 48
        entities:
          # - group.pi_hole_statistics
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
          - sensor.pi_hole_dns_queries_cached
          - sensor.pi_hole_dns_queries_forwarded
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_dns_unique_clients
          - sensor.pi_hole_domains_blocked
          - sensor.pi_hole_dns_unique_domains

  - title: Vacuum
    cards:
      - type: picture-elements
        image: /local/my_config/home_map.jpg
        # image: /local/floorplan.png
        elements:

          - type: state-icon
            tap_action:
              action: more-info
            entity: vacuum.xiaomi_vacuum
            style:
              top: 57%
              left: 23%
              "--paper-item-icon-color": black
      - type: glance
        entities:
          - entity: input_number.vacuum_xiaomi_dust_clean_left
            name: Bin dust left
            hold_action:
              action: call-service
              service: input_number.set_value
              service_data:
                entity_id: input_number.vacuum_xiaomi_dust_clean_left
                value: "{{ state_attr('input_number.vacuum_xiaomi_dust_clean_left', 'max') }}"
          - entity: group.vacuum_room
            name: Vacuum room

      - type: history-graph
        title: 'Aspiradora'
        hours_to_show: 48
        entities:
          # - group.pi_hole_statistics
          - vacuum.xiaomi_vacuum
          - input_number.vacuum_xiaomi_dust_clean_left
  - title: Power Sockets
    cards:
      - type: glance
        title: Enchufe Cocina Doble (Izq.)
        entities:
          - entity: timer.power_socket_double_001_left
          - entity: input_datetime.timer_power_socket_double_001_left
            # name: Bin dust left
            # hold_action:
            #   action: call-service
            #   service: input_number.set_value
            #   service_data:
            #     entity_id: input_number.vacuum_xiaomi_dust_clean_left
            #     value: "{{ state_attr('input_number.vacuum_xiaomi_dust_clean_left', 'max') }}"
      - type: glance
        title: Enchufe Cocina Doble (Der.)
        entities:
          - entity: timer.power_socket_double_001_right
          - entity: input_datetime.timer_power_socket_double_001_right

  - title: Flora
    cards:
      - type: history-graph
        title: 'Battery (24h)'
        hours_to_show: 24
        entities:
          # - group.home_speed
          - sensor.flora_001_battery
      - type: history-graph
        title: 'Light Intensity (24h)'
        hours_to_show: 24
        entities:
          # - group.home_speed
          - sensor.flora_001_light_intensity
      - type: history-graph
        title: 'Temperature (24h)'
        hours_to_show: 24
        entities:
          # - group.home_speed
          - sensor.flora_001_temperature
      - type: history-graph
        title: 'Moisture (24h)'
        hours_to_show: 24
        entities:
          # - group.home_speed
          - sensor.flora_001_moisture
      - type: history-graph
        title: 'Conductivity (24h)'
        hours_to_show: 24
        entities:
          # - group.home_speed
          - sensor.flora_001_conductivity
