# input_boolean:
  centinel_mode:
    name: Centinel Mode
    icon: mdi:shield-home
    initial: off
  home_recently_extended_away:
    name: Home Recently Extended Away
    icon: mdi:home-alert
    initial: off
