# script:
  notify_in_home_or_all:
    alias: "Notify person in home or all"
    fields:
      title: &fields_conf
        required: false
      message: *fields_conf
      data: *fields_conf
    sequence:
      # Notify to person in home or by default, Manolo (then we notify to Monica)
      - service: >
          {% if (is_state('sensor.manolo_status', 'Home') or is_state('sensor.manolo_status', 'Just Arrived')) %}
            notify.manolo
          {% elif (is_state('sensor.monica_status', 'Home') or is_state('sensor.monica_status', 'Just Arrived')) %}
            notify.monica
          {% else %}
            notify.manolo
          {% endif %}
        data: &notify-telegram-message
          title: '*{{ title }}*'
          message: '{{ message }}'
          data: >
            {% if data is defined %}
              {{data}}
            {% else %}
              {}
            {% endif %}
      # Check if both in the same state to continue notifying
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ (is_state('sensor.manolo_status', 'Home') or is_state('sensor.manolo_status', 'Just Arrived')) == (is_state('sensor.monica_status', 'Home') or is_state('sensor.monica_status', 'Just Arrived')) }}"
      - service: notify.monica
        data: *notify-telegram-message
