# script:
  notify_in_home_or_all:
    alias: "Notify person in home or all"
    sequence:
      # Notify to person in home or by default, Manolo
      - service_template: >
          {% if (is_state('sensor.manolo_status', 'Home') or is_state('sensor.manolo_status', 'Just Arrived')) %}
            notify.manolo
          {% elif (is_state('sensor.monica_status', 'Home') or is_state('sensor.monica_status', 'Just Arrived')) %}
            notify.monica
          {% else %}
            notify.manolo
          {% endif %}
        data_template: &notify-telegram-message
          title: '*{{ title }}*'
          message: '{{ message }}'
          data:
            inline_keyboard: '{{keyboard || []}}'
      # Check if both in the same state to continue notifying
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ (is_state('sensor.manolo_status', 'Home') or is_state('sensor.manolo_status', 'Just Arrived')) == (is_state('sensor.monica_status', 'Home') or is_state('sensor.monica_status', 'Just Arrived')) }}"
      - service: notify.monica
        data_template: *notify-telegram-message
