# mqtt:
#   sensor:
    - name: "man-002 Voltage"
      state_topic: "man-002/espurna/voltage"
      qos: "1"
      # icon:
      # availability_topic
      # payload_available
      # value_template: "{{ value_json.Voltage }}"
      # device
      unit_of_measurement: "V"
      device:
        identifiers: man-002
        name: Wachine machine power socket
    - name: "man-002 Current A"
      qos: "1"
      state_topic: "man-002/espurna/current"
      # value_template: "{{ value_json.Today }}"
      unit_of_measurement: "A"
      device:
        identifiers: man-002
        name: Wachine machine power socket
    - name: "man-002 Energy"
      qos: "1"
      state_topic: "man-002/espurna/energy"
      # value_template: "{{ value_json.Today }}"
      unit_of_measurement: "kWh"
      device:
        identifiers: man-002
        name: Wachine machine power socket
    - name: "man-002 Power"
      qos: "1"
      state_topic: "man-002/espurna/power"
      # value_template: "{{ value_json.Power }}"
      unit_of_measurement: "W"
      device:
        identifiers: man-002
        name: Wachine machine power socket
    - name: "man-002 Power factor"
      qos: "1"
      state_topic: "man-002/espurna/factor"
      # value_template: "{{ value_json.Voltage }}"
      unit_of_measurement: "%"
      device:
        identifiers: man-002
        name: Wachine machine power socket
