# binary_sensor:
  - platform: trend
    sensors:
      'environment_001_temperature_falling':
        entity_id: sensor.ble_temperature_environment_001
        sample_duration: 7200
        max_samples: 120
        invert: true
        # min_gradient: -0.0008
        device_class: cold

      'environment_001_temperature_rising':
        entity_id: sensor.ble_temperature_environment_001
        sample_duration: 7200
        max_samples: 120
        # min_gradient: 0.0008
        device_class: heat
