# homeassistant:
#   customize:
    sensor.ble_humidity_environment_001: &customization-sensor-001
      friendly_name: sensor-001

    sensor.ble_temperature_environment_001: *customization-sensor-001
    sensor.ble_battery_environment_001: *customization-sensor-001
