# homeassistant:
#   customize:
    sensor.mi_h_a4c1385cc12a: &customization-sensor-001
      friendly_name: sensor-001

    sensor.mi_t_a4c1385cc12a: *customization-sensor-001
    sensor.mi_batt_a4c1385cc12a: *customization-sensor-001
