version: "2.4"
services:
    home-assistant:
        # container_name: home-assistant
        hostname: woody-docker_home-assistant
        image: homeassistant/home-assistant:0.108.6
        depends_on:
          - postgres
        ports:
            - 0.0.0.0:8123:8123
        volumes:
            # Config files
            - ./home_assistant-config:/config

        environment:
            - TZ="Europe/Madrid"
        restart: unless-stopped
        # That it's useful to use bluetooth devices in server
        network_mode: "host"


    postgres:
        image: postgres:11.4-alpine
        restart: unless-stopped
        ports:
            - 127.0.0.1:5432:5432
            # - 0.0.0.0:5432:5432
        volumes:
          # Must be declared as external volume
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    mqtt:
        image: eclipse-mosquitto:1.6
        restart: unless-stopped
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto-config/:/mosquitto/config/:ro

