version: "2.4"
services:
    home-assistant:
        # container_name: home-assistant
        hostname: woody-docker_home-assistant
        image: homeassistant/home-assistant:0.103.5
        depends_on:
          - postgres
        ports:
            - 0.0.0.0:8123:8123
        volumes:
            # Config files
            - ./home_assistant-config:/config

        environment:
            - TZ="Europe/Madrid"
        restart: unless-stopped
        # That it's useful to use bluetooth devices in server
        network_mode: "host"


    postgres:
        image: postgres:11.4-alpine
        restart: unless-stopped
        ports:
            - 127.0.0.1:5432:5432
            # - 0.0.0.0:5432:5432
        volumes:
          # Must be declared as external volume
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    emqx:
        # name: mqtt
        image: emqx/emqx:v3.2.1
        restart: unless-stopped
        ports:
            - 1883:1883
            - 8083:8083
            - 18083:18083
            # - 8080:8080
        environment:
            - EMQX_ALLOW_ANONYMOUS=true
            # - EMQX_ALLOW_ANONYMOUS=false
            - EMQX_NAME=woody-mqtt
            # - EMQX_LOADED_PLUGINS=emqx_management | emqx_auth_redis | emqx_recon | emqx_retainer | emqx_dashboard
            ## Dashboard
            # dashboard.default_user.login
            - EMQX_DASHBOARD__DEFAULT__USER__LOGIN=manolo
            # dashboard.default_user.password=public
            - EMQX_DASHBOARD__DEFAULT__USER__PASSWORD=${EMQX_DASHBOARD__DEFAULT__USER__PASSWORD}
            ## AUTH
            # 

