version: "2.4"
services:
    home-assistant:
        # container_name: home-assistant
        hostname: woody-docker_home-assistant
        build:
            context: home_assistant/
        depends_on:
          - postgres
        # ports:
        #     - 0.0.0.0:8123:8123
        volumes:
            # Config files
            - ./home_assistant/config/:/config/
            - ./home_assistant/HA-custom-www/my-config/:/HA-custom-www/my-config/
            - /run/dbus:/run/dbus:ro
        devices:
            # Zigbee dongle
            - /dev/ttyUSB0:/dev/ttyUSB0
        environment:
            - TZ="Europe/Madrid"
                # Reduce logging verbosity caused by ddwrt recurrent requests
            - PYTHONWARNINGS=ignore:Unverified HTTPS request is being made to host '192.168.200.1'
        restart: unless-stopped
        stop_grace_period: 5m
        # That it's useful to use bluetooth devices in server
        network_mode: "host"
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
            - "traefik.http.routers.home-assistant.rule=Host(`${EXTERNAL_DOMAIN}`)"
            - "traefik.http.routers.home-assistant.entrypoints=websecure"
            - "traefik.http.routers.home-assistant.tls.certresolver=principal"
            - "traefik.http.routers.home-assistant.tls.domains[0].sans=${EXTERNAL_WILDCARD_DOMAIN}"

    esphome:
        image: esphome/esphome:2025.2.2
        restart: unless-stopped
        # ports:
        #     - 0.0.0.0:6052:6052
        ## Required to be able to auto-discover devices in the network
        network_mode: "host"
        volumes:
            - ./esphome/:/config:rw
            # Use local time for logging timestamps
            - /etc/localtime:/etc/localtime:ro
        environment:
            - USERNAME=${ESPHOME_DASHBOARD_USERNAME}
            - PASSWORD=${ESPHOME_DASHBOARD_PASSWORD}


    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        ports:
            - 127.0.0.1:5432:5432
            # - 0.0.0.0:5432:5432
        stop_grace_period: 5m
        volumes:
          # Must be declared as external volume
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    mqtt:
        image: eclipse-mosquitto:2.0.18
        restart: unless-stopped
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto-config/:/mosquitto/config/:ro

    vacuum_map:
        # Valetudo PNG (to transforma vacuum map to PNG)
        # https://github.com/erkexzcx/valetudopng
        image: ghcr.io/erkexzcx/valetudopng:v1.0.17
        restart: unless-stopped
        volumes:
            - ./vacuum_map/config_01.yml:/config.yml:ro
