version: "2.4"
services:
  wallabag:
    image: wallabag/wallabag:2.6.10
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://${WALLABAG_EXTERNAL_DOMAIN}
      - SYMFONY__ENV__SERVER_NAME="MoMa's Wallabag"
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_PATH=/var/www/wallabag/data/db/wallabag.sqlite
      # - SYMFONY__ENV__MAILER_HOST=${MAILER_HOST:-127.0.0.1}
      # - SYMFONY__ENV__MAILER_USER=${MAILER_USER:-null}
      # - SYMFONY__ENV__MAILER_PASSWORD=${MAILER_PASSWORD:-null}
      # - SYMFONY__ENV__FROM_EMAIL=${FROM_EMAIL:-wallabag@example.com}
      - SYMFONY__ENV__SECRET=${WALLABAG_SECRET:?Define a secret please}
      # Default admin credentials (change on first login)
      - SYMFONY__ENV__FOSUSER_INITIAL_USERNAME=${WALLABAG_ADMIN_USER:-wallabag}
      - SYMFONY__ENV__FOSUSER_INITIAL_PASSWORD=${WALLABAG_ADMIN_PASSWORD:-wallapass}
      - SYMFONY__ENV__FOSUSER_INITIAL_EMAIL=${WALLABAG_ADMIN_EMAIL:-admin@wallabag.local}
    volumes:
      - ./data/wallabag/images:/var/www/wallabag/web/assets/images
      - ./data/wallabag/data:/var/www/wallabag/data
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.wallabag.loadbalancer.server.port=80"
      - "traefik.http.routers.wallabag.rule=Host(`${WALLABAG_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.wallabag.entrypoints=websecure"
      - "traefik.http.routers.wallabag.tls.certresolver=principal"
      - "traefik.http.routers.wallabag.tls.domains[0].sans=${EXTERNAL_WILDCARD_DOMAIN}"
  
      # # Security headers
      # - "traefik.http.middlewares.wallabag-security-headers.headers.browserXssFilter=true"
      # - "traefik.http.middlewares.wallabag-security-headers.headers.contentTypeNosniff=true"
      # - "traefik.http.middlewares.wallabag-security-headers.headers.forceSTSHeader=true"
      # - "traefik.http.middlewares.wallabag-security-headers.headers.stsIncludeSubdomains=true"
      # - "traefik.http.middlewares.wallabag-security-headers.headers.stsPreload=true"
      # - "traefik.http.middlewares.wallabag-security-headers.headers.stsSeconds=31536000"
      # - "traefik.http.routers.wallabag.middlewares=wallabag-security-headers"

networks:
  reverse-proxy:
    # External network created by reverse-proxy setup
    external: true
  internal:
