# automation:


  - alias: AUT-Washing machine should power on
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.washing_machine_power_on_in
    action:
      - service: timer.cancel
        target:
          entity_id: timer.washing_machine_power_on_in
        # If the washing machine was properly ready, is going to auto turn-on in next seconds
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: 'Off'
      - service: switch.turn_on
        target:
          entity_id:
            - switch.man_002



  ############################################
  #
  # Logic to know washing machine status checking the power consumption
  # If you would like to check a better example, check the automation.yaml.old
  #
  ############################################


  # When power is detected, and the washing machine is not in 
  # the Running state, change the status of the washing machine
  # to Running. 
  # The status check will ensure we don't try to put the state 
  # to Running each time the power level changes, and we're already
  # in the Running state.
  - alias: AUT-Washing machine Running
    trigger:
      - platform: numeric_state
        entity_id: sensor.man_002_current_a
        above: 1
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.washing_machine_status
          state:
            - 'Off'
            - 'Finishing'
            - 'Clean'
            - 'Scheduled'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Washing


  # Wait 8 minutes for us when low power is detected before said
  # that washing machine has finished. This way, if the 
  # washing machine is in between cycles and the power drops, we 
  # won't mark the washing machine cycle as finished too early.
  - alias: AUT-Washing machine Clean
    trigger:
      - platform: numeric_state
        entity_id: sensor.man_002_current_a
        below: 0.001
        #above: 0.001
        for:
          minutes: 8
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state:
            - 'Washing'
            - 'Finishing'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Clean


  # If the state was clean and we receive some power, we turn on to empty it
  # so we change the status to emptying
  - alias: AUT-Washing machine Emptying
    trigger:
      - platform: numeric_state
        entity_id: sensor.man_002_current_a
        above: 0.001
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state:
            - 'Clean'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: Emptying

  # When no power is detected, and the washing machine is in 
  # a state different of 'Off' state or 'Clean', change the status of 
  # the washing machine to 'Off'.
  - alias: AUT-Washing machine Off
    trigger:
      - platform: numeric_state
        entity_id: sensor.man_002_current_a
        below: 0.001
        for:
          minutes: 15
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washing_machine_status
          state:
            # - 'Scheduled'
            # - 'Washing'
            # - 'Clean'
            - 'Emptying'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: 'Off'

  - alias: AUT-Washing machine Force Off
    trigger:
      - platform: event
        event_type: telegram_command
        event_data: &telegram_washine_machine_empty
          command: "/washing_machine_already_empty"
      - platform: event
        event_type: telegram_callback
        event_data: *telegram_washine_machine_empty
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washing_machine_status
          option: 'Off'
