
schedule_washing_machine:
  alias: "Schedule washing machine"
  sequence:
    # Washing machine is running so we need to power of and reschedule the start time
    - service: switch.turn_off
      target:
        entity_id:
          - switch.man_002
    ## Put the timer and notify of the scheduler
    - service: timer.start
      entity_id: timer.washing_machine_power_on_in
      data:
        duration: "{{states('input_datetime.input_timer_washing_machine_power_on_in)'}}"
      ### TODO: Manually change the state of the washing machine to a new one, scheduled
    - delay:
        seconds: 5
    - service: script.notify_in_home_or_all
      data:
        title: 'Washing machine correctly scheduled'
        message: >
          All is in place. Your washing machine was power off waiting till {{ state_attr('timer.washing_machine_power_on_in','finishes_at') }}
