# template:
  - sensor:
    - name: Washing Machine
      unique_id: washing_machine_status
      default_entity_id: sensor.washing_machine_status
      state: '{{ states.input_select.washing_machine_status.state }}'
