# automation:
  - alias: AUT-Notify home connect entity finish(Testing)
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: home_connect_alt_event
        id: input_event
    action:
      - service: script.notify_in_home_or_all
        data:
          title: 'An event was triggered from home connect'
          message: >
            Event: `{{ trigger.event }}`
            Event.Data: `{{ trigger.event.data }}`

