version: "2.4"
services:
  traefik:
    image: traefik:v3.4.4
    container_name: reverse-proxy_traefik
    restart: always
    ports:
      - "192.168.200.7:8080:8080"
      - "192.168.200.7:80:80"
      - "192.168.200.7:443:443"
      - "192.168.200.7:853:853"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./letsencrypt/:/letsencrypt/
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./file-dynamic-conf/:/etc/traefik/file-dynamic-conf/:ro
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - net-reverse-proxy
    environment: 
      - TRAEFIK_CERTIFICATESRESOLVERS_PRINCIPAL_ACME_EMAIL=${TRAEFIK_CERTIFICATESRESOLVERS_PRINCIPAL_ACME_EMAIL:-example@abc.com}
      - TRAEFIK_CERTIFICATESRESOLVERS_OLDDOMAIN_ACME_EMAIL=${TRAEFIK_CERTIFICATESRESOLVERS_PRINCIPAL_ACME_EMAIL:-example@abc.com}
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - DESEC_TOKEN=${DESEC_TOKEN}
      - DESEC_POLLING_INTERVAL=240s
      - DESEC_PROPAGATION_TIMEOUT=500s
        # Looks like desec is having problems creating CNAME entries used to validate wildcard certs
      - LEGO_DISABLE_CNAME_SUPPORT=true

networks:
  net-reverse-proxy:
    # Aims to create a network called "reverse-proxy" to reuse in others containers to be routed by reverse-proxy
    # This network must be created before start. `docker network create reverse-proxy`
    name: reverse-proxy
    external: true
