## traefik.yml

global:
  checkNewVersion: True
  # sendAnonymousUsag: True

# log:
#   level: DEBUG

accessLog: {}

entryPoints:
  web:
    address: ":80"
    ## Redirect all http to https
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  dns-tls:
    address: ":853"


# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///tmp/docker.sock"
    exposedbydefault: False
    # defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  file:
    directory: "/etc/traefik/file-dynamic-conf/"

# API and dashboard configuration
api:
  insecure: True
  # Access to http://192.168.200.7:8080/dashboard/
  dashboard: True

# Enable Let's Encrypt (wildcard/dns level)
certificatesResolvers:
  principal:
    acme:
      storage: /letsencrypt/acme.json
      ## Used as env variable
      # email: xyz@example.con
      ## With the next flag we indicate that we would like to generate the certificate with that root cert that is valid until "04 Jun 2035"
      preferredChain: 'ISRG Root X1'
      dnsChallenge:
        provider: duckdns
