title: Cosas encendidas
type: entity-filter
show_header_toggle: true
entities:
  - entity: switch.85304541b4e62d735f80_1
    name: Enchufe cocina doble izq.
  - entity: switch.85304541b4e62d735f80_2
    name: Enchufe cocina doble der.
  - entity: switch.man_001
    name: Enchufe luz salón
  # - entity: switch.02007254dc4f22ff4f45
  #   s/n: xxxx...xx 3401
  #   name: Luz salón
  - device_tracker.print_canon_mx920
  - sensor.washing_machine_status
  - vacuum.xiaomi_vacuum
  - entity: fan.dyson_01
    name: Dyson 01 Fan
  - plant.flora_001
  - entity: switch.adguard_protection
    name: AdGuard - Bloqueo de anuncios
    state_filter:
      - "off"
state_filter:
  - "on"
  - "home"
  # sensor.washing_machine_status
  - "Scheduled"
  - "Washing"
  - "Finishing"
  - "Clean"
  # vacuum.xiaomi_vacuum
  - "cleaning"
  - "returning"
  - "error"
  - "idle"
  - "paused"
  # Plant
  - "problem"
