title: Cosas encendidas
type: entity-filter
show_header_toggle: true
entities:
  - entity: switch.man_003_left
    name: Enchufe cocina doble izq.
  - entity: switch.man_003_right
    name: Enchufe cocina doble der.
  - entity: switch.man_004
    name: Luz entrada
  - entity: switch.man_001
    name: Enchufe luz salón
  # - entity: switch.02007254dc4f22ff4f45
  #   s/n: xxxx...xx 3401
  #   name: Luz salón
  - device_tracker.print_canon_mx920
  - entity: sensor.washing_machine_status
    tap_action: !include ../utils/washing-machine-card.yaml
  - light.midesklamp1s_01
  - vacuum.valetudo_roborocks5
  - group.nighstand_bedroom_lights
  - entity: input_number.vacuum_xiaomi_dust_clean_left
    name: "[Vacuum] Bin dust left"
    type: button
    state_filter:
      - operator: '<'
        value: 10
  - entity: fan.dyson_01
    name: Dyson 01 Fan
  - entity: sensor.mini_timers
    name: Kitchen timer
    state_filter: &google_home_enabled
      - operator: '!='
        value: unavailable
  - entity: sensor.mini_alarms
    name: Kitchen alarm
    state_filter: *google_home_enabled
  - entity: media_player.sony_bravia_tv
    name: Tele salón
    tap_action: !include ../utils/tv-card.yaml
  - entity: media_player.mini
    name: Mini (cocina)
  # We should use the ID of the new integration but it contains serial id
  - entity: sensor.lavavajillas_operation_state
    name: Lavavajillas
    icon: mdi:dishwasher
    state_filter:
      - operator: '!='
        value: 'Ready'
  # - plant.flora_001
  - entity: switch.adguard_protection
    name: AdGuard - Bloqueo de anuncios
    state_filter:
      - "off"
  - entity: sensor.ups_status
    state_filter:
      - operator: '!='
        value: 'ONLINE'
  - entity: sensor.ups_battery
    name: "[UPS] Battery status"
    icon: mdi:home-battery-outline
    state_filter:
      - operator: '<'
        value: 99
state_filter:
  - "on"
  - "home"
  - "playing"
  # sensor.washing_machine_status
  - "Scheduled"
  - "Washing"
  - "Finishing"
  - "Clean"
  - "Emptying"
  # vacuum.valetudo_roborocks5
  - "cleaning"
  - "returning"
  - "error"
  - "idle"
  - "paused"
  # Plant
  - "problem"
