type: horizontal-stack
cards:
  - type: custom:mushroom-template-card
    entity: sensor.manolo_status
    primary: Manolo
    secondary: "{{ states('sensor.manolo_status') }}"
    icon: >
      {% set s = states('sensor.manolo_status') %}
      {% if   s == 'Home'          %}mdi:home
      {% elif s == 'Just Arrived'  %}mdi:home-import-outline
      {% elif s == 'Just Left'     %}mdi:home-export-outline
      {% elif s == 'Away'          %}mdi:map-marker-outline
      {% elif s == 'Extended Away' %}mdi:map-marker-off-outline
      {% else %}mdi:help-circle-outline{% endif %}
    icon_color: >
      {% set s = states('sensor.manolo_status') %}
      {% if   s == 'Home'          %}green
      {% elif s == 'Just Arrived'  %}light-green
      {% elif s == 'Just Left'     %}orange
      {% elif s == 'Away'          %}red
      {% elif s == 'Extended Away' %}deep-orange
      {% else %}disabled{% endif %}
    tap_action:
      action: more-info

  - type: custom:mushroom-template-card
    entity: sensor.monica_status
    primary: Mónica
    secondary: "{{ states('sensor.monica_status') }}"
    icon: >
      {% set s = states('sensor.monica_status') %}
      {% if   s == 'Home'          %}mdi:home
      {% elif s == 'Just Arrived'  %}mdi:home-import-outline
      {% elif s == 'Just Left'     %}mdi:home-export-outline
      {% elif s == 'Away'          %}mdi:map-marker-outline
      {% elif s == 'Extended Away' %}mdi:map-marker-off-outline
      {% else %}mdi:help-circle-outline{% endif %}
    icon_color: >
      {% set s = states('sensor.monica_status') %}
      {% if   s == 'Home'          %}green
      {% elif s == 'Just Arrived'  %}light-green
      {% elif s == 'Just Left'     %}orange
      {% elif s == 'Away'          %}red
      {% elif s == 'Extended Away' %}deep-orange
      {% else %}disabled{% endif %}
    tap_action:
      action: more-info
