type: horizontal-stack
cards:
  - type: custom:mushroom-person-card
    entity: person.manolo
    icon: mdi:human-male
    use_entity_picture: true
    tap_action:
      action: more-info
  - type: custom:mushroom-person-card
    entity: person.monica
    icon: mdi:human-female
    use_entity_picture: true
    tap_action:
      action: more-info
