# title: House
type: picture-elements
image: /local/my_config/home_map.png
# image: /local/floorplan.png
elements:
  - type: state-icon
    tap_action:
      action: toggle
    entity: light.living_room_light
    style:
      top: 35%
      left: 50%
      "--paper-item-icon-color": black
  - type: state-icon
    tap_action:
      action: more-info
    entity: group.power_socket_double_001
    # entity: group.vacuum_room
    style:
      top: 12%
      left: 94%
      "--paper-item-icon-color": black
  - type: state-icon
    tap_action:
      action: more-info
    hold_action:
      action: call-service
      service: switch.turn_on
      service_data:
        entity_id: switch.tv_samsung_key_power
    entity: group.tv_samsung
    icon: mdi:television-classic
    # state_filter:
    #   "off": --paper-item-icon-color=pink
    style:
      top: 62%
      left: 27%
      "--paper-item-icon-color": black
  - type: state-icon
    tap_action:
      action: more-info
    entity: vacuum.xiaomi_vacuum
    style:
      top: 35%
      left: 46%
      "--paper-item-icon-color": black
  - type: state-icon
    tap_action:
      action: more-info
    entity: sensor.washing_machine_status
    style:
      top: 42%
      left: 93%
      "--paper-item-icon-color": black
  - type: conditional
    tap_action:
      action: none
    conditions:
      - entity: device_tracker.print_canon_mx920
        state: home
    elements:
      - type: state-icon
        tap_action:
          action: more-info
        entity: device_tracker.print_canon_mx920
        style:
          top: 80%
          left: 80%
          "--paper-item-icon-color": yellow
  - type: state-icon
    tap_action:
      action: more-info
    entity: plant.flora_001
    # entity: group.vacuum_room
    style:
      top: 42%
      left: 7%
      "--paper-item-icon-color": black
  # - type: state-label
  #   entity: sensor.outside_temperature
  #   style:
  #     top: 45%
  #     left: 88%
  # - type: service-button
  #   title: Turn lights off
  #   style:
  #     top: 95%
  #     left: 60%
  #   service: homeassistant.turn_off
  #   service_data:
  # Didn't work from 0.104: https://www.home-assistant.io/blog/2020/01/15/release-104/
  #     entity_id: group.all_lights
  - type: icon
    icon: mdi:home
    tap_action:
      action: navigate
      navigation_path: /lovelace/0
    style:
      top: 10%
      left: 10%
