# automation:
  - alias: AUT-Sunset
    initial_state: 'on'
    trigger:
      - platform: state
        to: 'Just Arrived'
        entity_id:
          - sensor.home_occupancy_status
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    condition:
      - condition: sun
        after: sunset
        after_offset: '-00:30:00'
      - condition: time
        after: '13:00:00'
        before: '03:00:00'
      - condition: state
        state: 'Just Arrived'
        entity_id:
          - sensor.home_occupancy_status
    action:
      - service: scene.turn_on
        entity_id: scene.night
      - service: homeassistant.turn_on
        entity_id: script.notify_in_home_or_all
        data:
          variables:
            title: 'Auto turned on light'
            message: 'Light turned on by automation `AUT-Sunset`'
