# automation:
  - alias: AUT-Sunset
    initial_state: 'on'
    trigger:
      - platform: state
        to: 'Just Arrived'
        entity_id:
          - sensor.home_occupancy_status
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    condition:
      - condition: sun
        after: sunset
        after_offset: '-00:30:00'
      - condition: time
        after: '13:00:00'
        before: '03:00:00'
      - condition: state
        state:
          - 'Just Arrived'
          - 'Home'
        entity_id:
          - sensor.home_occupancy_status
    action:
      - service: scene.turn_on
        entity_id: scene.night
      - service: homeassistant.turn_on
        entity_id: script.notify_in_home_or_all
        data:
          variables:
            title: 'Auto turned on light'
            message: 'Light turned on by automation `AUT-Sunset`'
            keyboard:
              - 'Turn off:/turn_off_scene_night'

  - alias: AUT-Telegram turn off scene night
    mode: restart
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: telegram_command
        event_data: &telegram_turn_off_scene_light
          command: "/turn_off_scene_night"
      - platform: event
        event_type: telegram_callback
        event_data: *telegram_turn_off_scene_light
    action:
      - service: scene.turn_off
        entity_id: scene.night
