# binary_sensor:
  # Now forced to be managed from UI. Release 2023.6
  # - platform: workday
  #   country: "ES"
  #   province: "AN"
  #   add_holidays:
  #     # 2021
  #     - "2021-12-24"
  #     - "2021-12-31"
  #     # 2022
  #     - "2022-05-04"
  #     - "2022-06-16"
  #     - "2022-12-24"
  #     - "2022-12-31"
