# template:
  - sensor:
    - name: amount_turned_on_entities_monitored_by_label
      unique_id: amount_turned_on_entities_monitored_by_label
      icon: mdi:lightbulb-on
      variables:
        entities_on: >
          expand(label_entities('monitorTurnedOn')) | selectattr('state', 'eq', 'on') | list | map(attribute='entity_id') | list
      state: >
        {{ entities_on | count }}
      attributes:
        entities_on: >
          {{ entities_on }}
      state_class: total
      unit_of_measurement: entities
