# google_assistant:
  # entity_config:

      ## Enabled entities
    switch.tv_samsung_key_mute: &tv-enabled
      room: Living Room
      expose: True

    switch.tv_samsung_key_power:
      <<: *tv-enabled
      aliases:
        - Tele
