# group:
  tv_samsung:
    name: TV
    icon: mdi:remote-tv
    entities:
      - switch.tv_samsung_key_power
      - switch.tv_samsung_key_mute
      - switch.tv_samsung_key_volumeup
      - switch.tv_samsung_key_volumedown
      - switch.tv_samsung_key_source
      - switch.tv_samsung_key_up
      - switch.tv_samsung_key_down
      - switch.tv_samsung_key_right
      - switch.tv_samsung_key_left
      - switch.tv_samsung_key_exit
      - switch.tv_samsung_key_enter
      - switch.tv_samsung_dual
      - switch.tv_samsung_key_0
      - switch.tv_samsung_key_1
      - switch.tv_samsung_key_2
      - switch.tv_samsung_key_3
      - switch.tv_samsung_key_4
      - switch.tv_samsung_key_5
      - switch.tv_samsung_key_6
      - switch.tv_samsung_key_7
      - switch.tv_samsung_key_8
      - switch.tv_samsung_key_9
      - switch.tv_samsung_key_channeldown
      - switch.tv_samsung_key_channelup
      - switch.tv_samsung_pre_ch
      - switch.tv_samsung_key_green
      - switch.tv_samsung_key_yellow
      - switch.tv_samsung_key_blue
      - switch.tv_samsung_key_menu
      - switch.tv_samsung_key_info
      - switch.tv_samsung_pip
      - switch.tv_samsung_key_102nd
      - switch.tv_samsung_key_subtitle
      - switch.tv_samsung_p_mode
      - switch.tv_samsung_s_mode
      - switch.tv_samsung_ttx_mix
      - switch.tv_samsung_p_size
      - switch.tv_samsung_still
      - switch.tv_samsung_tv_dtv
      - switch.tv_samsung_key_rewind
      - switch.tv_samsung_key_stop
      - switch.tv_samsung_key_playpause
      - switch.tv_samsung_key_fastforward
      - switch.tv_samsung_key_info_2
      - switch.tv_samsung_ch_mgr
      - switch.tv_samsung_key_red
      - switch.tv_samsung_srs
      - switch.tv_samsung_key_vcr
      - switch.tv_samsung_cable
      - switch.tv_samsung_key_tv
      - switch.tv_samsung_key_dvd
      - switch.tv_samsung_stb
      - switch.tv_samsung_wiselink
      - switch.tv_samsung_d_menu
