# switch:
  - # friendly_name: IR living room
    platform: broadlink
    #host: 192.168.200.51
    mac: !secret switch_ir_living_room_mac
    #type: rm_mini
    switches:
      - name: "TV DUAL"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISEhISEhISEhISEjcSNxI3EjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV Source"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEhISEhISEhISEhISEhISNxI3EjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV POWER"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISEhISEhISEhISEjcSEhI3EjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_1"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_2"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_3"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSEhISEhISEhISEjcSEhISEjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV Volume up"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EjcSEhISEhISEhISEhISEhISEjcSNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_4"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISNxISEhISEhISEjcSNxI3EhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_5"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEhISNxISEhISEhISEhISNxI3EhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_6"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV Volume down"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISNxISEhISEhISEhISEhI3EhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_7"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEjcSNxISEhISEhISEjcSNxISEhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_8"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSNxISEhISEhISEhISNxISEhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_9"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSNxISEhISEhISEjcSEhISEhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV Mute"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EjcSNxISEhISEhISEhISEhISEhISNxI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_CHANNELDOWN"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISEhI3EhISEhISEjcSNxI3EjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_0"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_CHANNELUP"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV PRE-CH"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISEhI3EhISEhISEhISEhI3EjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_GREEN"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEjcSEhI3EhISEhISEjcSNxISEjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_YELLOW"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_BLUE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSEhI3EhISEhISEjcSEhISEjcSEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_MENU"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISNxI3EhISEhISEjcSEhI3EhISEhI3EjcSNxIABfgNBQ=='
      - name: "TV KEY_INFO"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EjcSNxI3EhISEhISEhISEhISEhISEhI3EjcSNxIABfgNBQ=='
      - name: "TV PIP"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISEhISEjcSEhISEjcSNxI3EjcSNxISEjcSNxIABfgNBQ=='
      - name: "TV KEY_102ND"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISEhISEjcSEhISEhISEhI3EjcSNxISEjcSNxIABfgNBQ=='
      - name: "TV KEY_SUBTITLE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSEhISEjcSEhISEhISNxISEjcSNxISEjcSNxIABfgNBQ=='
      - name: "TV P.MODE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISNxISEjcSEhISEjcSNxI3EhISNxISEjcSNxIABfgNBQ=='
      - name: "TV S.MODE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISNxISEjcSEhISEhISEhI3EhISNxISEjcSNxIABfgNBQ=='
      - name: "TV TTX/MIX"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEjcSNxISEjcSEhISEjcSNxISEhISNxISEjcSNxIABfgNBQ=='
      - name: "TV KEY_EXIT"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSNxISEjcSEhISEhISNxISEhISNxISEjcSNxIABfgNBQ=='
      - name: "TV P.SIZE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSNxI3EjcSEhISEjcSEhISEhISEhISEjcSNxIABfgNBQ=='
      - name: "TV STILL"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EhISNxIABfgNBQ=='
      - name: "TV TV/DTV"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISEhISEhISNxISEhISEhI3EjcSNxI3EhISNxIABfgNBQ=='
      - name: "TV KEY_REWIND"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSEhISEhISNxISEhISNxISEjcSNxI3EhISNxIABfgNBQ=='
      - name: "TV KEY_STOP"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSEhISEhISNxISEjcSEhISEjcSNxI3EhISNxIABfgNBQ=='
      - name: "TV KEY_PLAYPAUSE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EjcSEhISEhISNxISEhISEhISEjcSNxI3EhISNxIABfgNBQ=='
      - name: "TV KEY_FASTFORWARD"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISNxISEhISNxISEjcSNxI3EhISNxI3EhISNxIABfgNBQ=='
      - name: "TV KEY_INFO_2"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EjcSNxISEhISNxISEhISEhISEhISNxI3EhISNxIABfgNBQ=='
      - name: "TV Up"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxIABfgNBQ=='
      - name: "TV Down"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEhISEhISEjcSNxISEhISNxI3EjcSNxISEhISNxIABfgNBQ=='
      - name: "TV Right"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISEhISEjcSNxISEjcSEhI3EjcSNxISEhISNxIABfgNBQ=='
      - name: "TV Left"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSEhISEjcSNxISEhISNxISEjcSNxISEhISNxIABfgNBQ=='
      - name: "TV Enter"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEhISNxISEjcSNxISEjcSNxI3EhISNxISEhISNxIABfgNBQ=='
      - name: "TV CH_MGR"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISNxISEjcSNxISEhISEhI3EhISNxISEhISNxIABfgNBQ=='
      - name: "TV KEY_RED"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEjcSNxISEjcSNxISEjcSNxISEhISNxISEhISNxIABfgNBQ=='
      - name: "TV SRS"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSNxISEjcSNxISEjcSEhISEhISNxISEhISNxIABfgNBQ=='
      - name: "TV KEY_VCR"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EhISNxI3EjcSNxISEjcSEhI3EhISEhISEhISNxIABfgNBQ=='
      - name: "TV CABLE"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EhISNxI3EjcSNxISEhISEhI3EhISEhISEhISNxIABfgNBQ=='
      - name: "TV KEY_TV"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxISEjcSNxI3EjcSNxISEhISNxISEhISEhISEhISNxIABfgNBQ=='
      - name: "TV KEY_DVD"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSNxI3EjcSNxISEjcSEhISEhISEhISEhISNxIABfgNBQ=='
      - name: "TV STB"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISNxI3EjcSNxI3EjcSNxISEhISEhISEhISEhISEhISNxIABfgNBQ=='
      - name: "TV WISELINK"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhISEjcSNxISEhISEhI3EjcSNxISEhISNxI3EjcSEhIABfgNBQ=='
      - name: "TV D.MENU"
        command_on: 'JgBGAJOTEjcSNxI3EhISEhISEhISEhI3EjcSNxISEhISEhISEhISEhI3EjcSNxISEhISEhI3EjcSEhISEhISNxI3EjcSEhIABfgNBQ=='
