name: 'Home Assistant container'
description: 'My Home Assistant container'
inputs:
  my_command:
    description: 'Command to execute'
    default: 'ls -alh'
  # my_command_02:
  #   description: 'Command to execute 02'
  # my_command_03:
  #   description: 'Command to execute 03'
  # my_command_04:
  #   description: 'Command to execute 04'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: '../../../home_automation/home_assistant/Dockerfile'
  args: |
    ${{ inputs.my_command }}
