name: 'Home Assistant container'
description: 'My Home Assistant container'
# inputs:
#   my_command:
#     description: 'Command to execute'
#     default: 'ls -alh'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: '../../../home_automation/home_assistant/Dockerfile'
  args:
    - /usr/local/bin/hass
    - -c=home_automation/home_assistant/config/
    - --script
    ## Must be in that way, if not, info=all fail
    - check_config
    - --info=all
#  ${{ inputs.my_command }}
