name: Auto Update components
on:
  schedule:
    # This is in UTC time
      # At 7 & 18 spanish time
    - cron: '2 5,16 * * *'
  # push:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.0.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
