name: Home Assistant CI
on: [push, pull_request]

jobs:
  check_syntax:
    name: Checking syntax
    # container:
    #   image: homeassistant/home-assistant:0.104.3
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare privates
        run: |
          set -ex
          mv home_automation/home_assistant/config/secrets.example.yaml home_automation/home_assistant/config/secrets.yaml
          mv home_automation/home_assistant/config/google_assistant_service_account.example.json home_automation/home_assistant/config/google_assistant_service_account.json
      # - name: quick-test
      #   run: |
      #     set -ex
      #     cd home_automation/home_assistant/
      #     sudo docker build \
      #       -t example \
      #       .

      #     sudo docker run --rm -i \
      #       --privileged \
      #       -v ${PWD}/config/:/config/ \
      #       -v ${PWD}/HA-custom-www/my-config/:/HA-custom-www/my-config/ \
      #       example \
      #       /usr/local/bin/hass -c=/config/ --script check_config --info=all

      - name: Test configuration
        uses: ./.github/actions/home-assistant
        # with:
        #   # command: 'hass -c home_automation/home_assistant/config/ --script check_config'
        #   # command: 'ls -alh home_automation/home_assistant/config/'
        #   my_command: 'ls -alh'
      # - name: Checking syntax
      #   uses: docker://homeassistant/home-assistant:0.109.6
      #   id: HA-check-syntax
      #   with:
      #     args: |
      #       hass -c home_automation/home_assistant-config/ --script check_config
