# That file contain each view of ui
- title: Home
  icon: mdi:home
  cards: !include_dir_list Home/
- title: Vacuum
  icon: mdi:robot-vacuum
  cards: !include Vacuum.yaml
- title: Climate
  icon: mdi:thermostat
  cards: !include Climate.yaml
- title: Energy
  icon: mdi:home-lightning-bolt-outline
  cards: !include Energy.yaml

- title: Net
  # icon: mdi:router-network
  icon: mdi:access-point-network
  cards: !include Net.yaml
- title: Server
  icon: mdi:server
  cards: !include Server.yaml
- title: Environment
  icon: mdi:coolant-temperature
  cards: !include Environment.yaml
# - title: Flora
#   icon: mdi:flower
#   cards: !include Flora.yaml



# Work in Progress section
- title: WIP
  icon: mdi:tools
  cards: !include WIP.yaml
