- type: thermostat
  name: Centralized AC
  entity: climate.centralized_ac
- type: vertical-stack
  title: 'Dyson Fan 01'
  cards:
    - type: horizontal-stack
      cards:
        - type: entities
          entities:
            - name: Fan
              entity: fan.dyson_01
        - type: entities
          entities:
            - name: Night Mode
              entity: switch.dyson_01_night_mode
            - name: Advanced
              entity: group.dyson_01_all
    - type: thermostat
      name: Hot control
      entity: climate.dyson_01
