- type: vertical-stack
  title: 'Last 24h'
  cards:
    ## Temperature
    - type: grid
      square: false
      columns: 2
      cards:
        - &environment-24h-card
          type: sensor
          graph: line
          detail: 2
          hours_to_show: 24
          entity: sensor.ble_temperature_flora_001
        - <<: *environment-24h-card
          entity: sensor.dyson_01_temperature
        - <<: *environment-24h-card
          entity: sensor.xiaomi_lywsd03mmc_z_01_temperatura
        - <<: *environment-24h-card
          entity: sensor.xiaomi_002_c421_temperature
        - <<: *environment-24h-card
          entity: sensor.xiaomi_003_5e2f_temperature
        - <<: *environment-24h-card
          entity: sensor.xiaomi_004_3c9a_temperature

    ## Humidity
    - type: grid
      square: false
      columns: 2
      cards:
        - <<: *environment-24h-card
          entity: sensor.dyson_01_humidity
        - <<: *environment-24h-card
          entity: sensor.xiaomi_lywsd03mmc_z_01_humedad
        - <<: *environment-24h-card
          entity: sensor.xiaomi_002_c421_humidity
        - <<: *environment-24h-card
          entity: sensor.xiaomi_003_5e2f_humidity
        - <<: *environment-24h-card
          entity: sensor.xiaomi_004_3c9a_humidity

- type: vertical-stack
  title: 'Last 7d'
  cards:
    ## Temperature
    - type: grid
      square: false
      columns: 2
      cards:
        - &environment-7d-card
          type: sensor
          graph: line
          detail: 1
          hours_to_show: 168
          entity: sensor.ble_temperature_flora_001
        - <<: *environment-7d-card
          entity: sensor.dyson_01_temperature
        - <<: *environment-7d-card
          entity: sensor.xiaomi_lywsd03mmc_z_01_temperatura
        - <<: *environment-7d-card
          entity: sensor.xiaomi_002_c421_temperature
        - <<: *environment-7d-card
          entity: sensor.xiaomi_003_5e2f_temperature
        - <<: *environment-7d-card
          entity: sensor.xiaomi_004_3c9a_temperature

    ## Humidity
    - type: grid
      square: false
      columns: 2
      cards:
        - <<: *environment-7d-card
          entity: sensor.dyson_01_humidity
        - <<: *environment-7d-card
          entity: sensor.xiaomi_lywsd03mmc_z_01_humedad
        - <<: *environment-7d-card
          entity: sensor.xiaomi_002_c421_humidity
        - <<: *environment-7d-card
          entity: sensor.xiaomi_003_5e2f_humidity
        - <<: *environment-7d-card
          entity: sensor.xiaomi_004_3c9a_humidity

    ## Battery
    - type: grid
      square: false
      columns: 2
      cards:
        - <<: *environment-7d-card
          entity: sensor.ble_battery_flora_001
        - <<: *environment-7d-card
          entity: sensor.xiaomi_lywsd03mmc_z_01_bateria
        - <<: *environment-7d-card
          entity: sensor.xiaomi_002_c421_battery
        - <<: *environment-7d-card
          entity: sensor.xiaomi_003_5e2f_battery
        - <<: *environment-7d-card
          entity: sensor.xiaomi_004_3c9a_battery
        - <<: *environment-7d-card
          entity: sensor.entry_door_sensor_battery
