- type: vertical-stack
  title: 'Last 24h'
  cards:
    ## Temperature
    - type: horizontal-stacl
      cards:
        - &environment-card
          type: sensor
          graph: line
          detail: 2
          hours_to_show: 24
          entity: sensor.mi_t_c47c8d6b1a91
        - <<: *environment-card
          entity: sensor.mi_t_a4c1385cc12a

    ## Humidity
    - type: horizontal-stacl
      cards:
        - <<: *environment-card
          entity: sensor.mi_h_a4c1385cc12a

    ## Battery
    - type: horizontal-stacl
      cards:
        - <<: *environment-card
          entity: sensor.mi_batt_c47c8d6b1a91
        - <<: *environment-card
          entity: sensor.mi_batt_a4c1385cc12a

- type: history-graph
  title: 'Humidity (24h)'
  hours_to_show: 24
  entities:
    - sensor.environment_001_humidity

- type: history-graph
  title: 'Battery (24h)'
  hours_to_show: 24
  entities:
    - sensor.environment_001_battery
