- type: horizontal-stack
  title: 'Temperature (24h)'
  cards:
    - &temperature-card
      type: sensor
      icon: mdi:thermometer
      graph: line
      unit: ºC
      detail: 2
      hours_to_show: 24
      entity: sensor.mi_t_c47c8d6b1a91
    - <<: *temperature-card
      entity: sensor.mi_t_a4c1385cc12a
- type: history-graph
  title: 'Humidity (24h)'
  hours_to_show: 24
  entities:
    - sensor.environment_001_humidity

- type: history-graph
  title: 'Battery (24h)'
  hours_to_show: 24
  entities:
    - sensor.environment_001_battery
