- type: vertical-stack
  title: 'Last 24h'
  cards:
    ## Temperature
    - type: horizontal-stack
      cards:
        - &environment-24h-card
          type: sensor
          graph: line
          detail: 2
          hours_to_show: 24
          entity: sensor.mi_t_c47c8d6b1a91
        - <<: *environment-24h-card
          entity: sensor.ble_temperature_environment_001

    ## Humidity
    - type: horizontal-stack
      cards:
        - <<: *environment-24h-card
          entity: sensor.ble_humidity_environment_001

    ## Battery
    - type: horizontal-stack
      cards:
        - <<: *environment-24h-card
          entity: sensor.mi_batt_c47c8d6b1a91
        - <<: *environment-24h-card
          entity: sensor.ble_battery_environment_001


- type: vertical-stack
  title: 'Last 7d'
  cards:
    ## Temperature
    - type: horizontal-stack
      cards:
        - &environment-7d-card
          type: sensor
          graph: line
          detail: 1
          hours_to_show: 168
          entity: sensor.mi_t_c47c8d6b1a91
        - <<: *environment-7d-card
          entity: sensor.ble_temperature_environment_001

    ## Humidity
    - type: horizontal-stack
      cards:
        - <<: *environment-7d-card
          entity: sensor.ble_humidity_environment_001

    ## Battery
    - type: horizontal-stack
      cards:
        - <<: *environment-7d-card
          entity: sensor.mi_batt_c47c8d6b1a91
        - <<: *environment-7d-card
          entity: sensor.ble_battery_environment_001
