- type: entities
  title: 'AdGuard DNS'
  entities:
    - switch.adguard_protection
    - sensor.adguard_average_processing_speed
    - sensor.adguard_dns_queries_blocked_ratio
    - sensor.adguard_dns_queries

- type: entities
  title: 'Router stats (Netdata)'
  entities:
    - sensor.router_cpu_usage
    - sensor.router_ram_used
    - sensor.router_load_1min
    - sensor.router_uptime
    - sensor.router_active_connections

- type: entities
  title: 'Internet Latency (FPing)'
  entities:
    - sensor.router_ping_google_avg
    - sensor.router_ping_google_max
    - sensor.router_ping_google_quality
    - sensor.router_ping_cloudflare_avg
    - sensor.router_ping_cloudflare_quality

- type: history-graph
  title: 'Internet Latency'
  hours_to_show: 24
  entities:
    - sensor.router_ping_google_avg
    - sensor.router_ping_cloudflare_avg

- type: entities
  title: 'WAN Traffic'
  entities:
    - sensor.router_wan_received
    - sensor.router_wan_sent

- type: history-graph
  title: 'WAN Bandwidth'
  hours_to_show: 5
  entities:
    - sensor.router_wan_received
    - sensor.router_wan_sent

- type: entities
  title: 'WiFi Traffic'
  entities:
    - sensor.router_wifi_5ghz_received
    - sensor.router_wifi_5ghz_sent
    - sensor.router_wifi_2_4ghz_received
    - sensor.router_wifi_2_4ghz_sent

- type: history-graph
  title: 'WiFi Bandwidth'
  hours_to_show: 5
  entities:
    - sensor.router_wifi_5ghz_received
    - sensor.router_wifi_5ghz_sent
    - sensor.router_wifi_2_4ghz_received
    - sensor.router_wifi_2_4ghz_sent

- type: entities
  title: 'LAN Traffic'
  entities:
    - sensor.router_lan_received
    - sensor.router_lan_sent

- type: history-graph
  title: 'Net Speed (Speedtest)'
  hours_to_show: 48
  entities:
    # - group.home_speed
    - sensor.speedtest_ping
    - sensor.speedtest_download
    - sensor.speedtest_upload

- type: history-graph
  title: 'Router System'
  hours_to_show: 5
  entities:
    - sensor.router_cpu_usage
    - sensor.router_ram_used
    - sensor.router_load_1min
# - type: history-graph
#   title: 'PiHole'
#   hours_to_show: 48
#   entities:
#     # - group.pi_hole_statistics
#     - sensor.pi_hole_ads_blocked_today
#     - sensor.pi_hole_ads_percentage_blocked_today
#     - sensor.pi_hole_dns_queries_cached
#     - sensor.pi_hole_dns_queries_forwarded
#     - sensor.pi_hole_dns_queries_today
#     - sensor.pi_hole_dns_unique_clients
#     - sensor.pi_hole_domains_blocked
#     - sensor.pi_hole_dns_unique_domains
