- type: picture-elements
  image: /local/my_config/home_map.png
  camera_image: camera.xiaomi_vacuum_map
  elements:

    - type: state-icon
      tap_action:
        action: more-info
      entity: vacuum.xiaomi_vacuum
      style:
        top: 63%
        left: 20%
        "--paper-item-icon-color": black
- type: glance
  entities:
    - entity: input_number.vacuum_xiaomi_dust_clean_left
      name: Bin dust left
      hold_action:
        action: call-service
        service: input_number.set_value
        service_data:
          entity_id: input_number.vacuum_xiaomi_dust_clean_left
          value: "{{ state_attr('input_number.vacuum_xiaomi_dust_clean_left', 'max') }}"
    - entity: group.vacuum_room
      name: Vacuum room

- type: history-graph
  title: 'Aspiradora'
  hours_to_show: 48
  entities:
    # - group.pi_hole_statistics
    - vacuum.xiaomi_vacuum
    - input_datetime.vacuum_last_full_clean
    - input_number.vacuum_xiaomi_dust_clean_left
