- type: glance
  entities:
    - entity: vacuum.xiaomi_vacuum
    - entity: input_number.vacuum_xiaomi_dust_clean_left
      name: Bin dust left
      hold_action:
        action: call-service
        service: input_number.set_value
        service_data:
          entity_id: input_number.vacuum_xiaomi_dust_clean_left
          value: "{{ state_attr('input_number.vacuum_xiaomi_dust_clean_left', 'max') }}"
    - entity: group.vacuum_room
      name: Vacuum room
- type: 'custom:xiaomi-vacuum-map-card'
  entity: vacuum.xiaomi_vacuum
  map_camera: camera.xiaomi_vacuum_map
  camera_calibration: true
- type: history-graph
  title: 'Aspiradora'
  hours_to_show: 48
  entities:
    # - group.pi_hole_statistics
    - vacuum.xiaomi_vacuum
    - input_datetime.vacuum_last_full_clean
    - input_number.vacuum_xiaomi_dust_clean_left
